fix(pkgdb): Assume main as workflow_dispatch base
Manually run workflows don't have a `github.base_ref` so this step
would fail with:

    Checking changed sources
    fatal: Needed a single revision
    Error: Process completed with exit code 128.

As seen in:

- https://github.com/flox/flox/actions/runs/8910119942/job/24468719478#step:4:29

And fixed, but failing for a different reason, in:

- https://github.com/flox/flox/actions/runs/8910586193/job/24470138139#step:4:30