fix: circular flox-activations dependency
Adding an actual reference to flox-activations in the activate script
causes the following error from `nix build .#flox-pkgdb`:
```
error: infinite recursion encountered
```

Currently we have the circular dependency chain flox-activations ->
rust-internal-deps -> flox-pkgdb -> flox-activation-scripts ->
flox-activations.

rust-internal-deps are compiled with different options than
flox-activations, so the Rust compilation of flox-activations already
doesn't depend on rust-internal-deps, and the dependency on
rust-internal-deps.envs was likely just due to copy-paste.

Remove the dependency of flox-activations -> rust-internal-deps to avoid
the circular dependency entirely.