chore: Fix cargo git
    error: failed to get `httpmock` as a dependency of package `flox-rust-sdk v0.0.0 (/Users/dcarley/projects/flox/flox/cli/flox-rust-sdk)`

    Caused by:
      failed to load source for dependency `httpmock`

    Caused by:
      Unable to update https://github.com/alexliesenfeld/httpmock.git

    Caused by:
      failed to clone into: /Users/dcarley/.cargo/git/db/httpmock-34683108cb38e0d7

    Caused by:
      failed to authenticate when downloading repository: git@github.com:alexliesenfeld/httpmock.git

      * attempted ssh-agent authentication, but no usernames succeeded: `git`

      if the git CLI succeeds then `net.git-fetch-with-cli` may help here
      https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

    Caused by:
      no authentication methods succeeded