refactor(fetcher): Use manifest->lockfile in test
In preparation for removing `Environment::manifest()` so that we stop
accidentally using unlocked and unmerged manifests.

Verified existing test with this change:

    diff --git a/cli/flox-rust-sdk/src/models/environment/fetcher.rs b/cli/flox-rust-sdk/src/models/environment/fetcher.rs
    index c0a71033..8809ae33 100644
    --- a/cli/flox-rust-sdk/src/models/environment/fetcher.rs
    +++ b/cli/flox-rust-sdk/src/models/environment/fetcher.rs
    @@ -101,7 +101,7 @@ impl IncludeFetcher {
             // Don't affect existing open remotes but still uses the same floxmeta.
             let tempdir =
                 tempfile::tempdir_in(&flox.temp_dir).map_err(EnvironmentError::CreateTempDir)?;
    -        let environment = RemoteEnvironment::new_in(flox, tempdir.path(), pointer)?;
    +        let environment = RemoteEnvironment::new(flox, pointer)?;

             let lockfile = environment
                 .existing_lockfile(flox)?

Which still causes it to fail with:

    thread 'models::environment::fetcher::test::fetch_remote' panicked at flox-rust-sdk/src/models/environment/fetcher.rs:397:9:
    assertion failed: `(left == right)`: fetch should not affect the generation of an already open environment

    Diff < left / right > :
     Lockfile {
         version: Version {
             value: 1,
         },
         manifest: Manifest {
             version: Version {
                 value: 1,
             },
             install: Install(
                 {},
             ),
             vars: Vars(
    <            {
    <                "foo": "bar",
    <            },
    >            {},
             ),
             hook: None,
             profile: None,
             options: Options {
                 systems: None,
                 allow: Allows {
                     unfree: None,
                     broken: None,
                     licenses: None,
                 },
                 semver: SemverOptions {
                     allow_pre_releases: None,
                 },
                 cuda_detection: None,
                 activate: ActivateOptions {
                     mode: None,
                 },
             },
             services: Services(
                 {},
             ),
             build: Build(
                 {},
             ),
             containerize: None,
             include: Include {
                 environments: [],
             },
         },
         packages: [],
         compose: None,
     }