fix(publish): Restrict ls-compression to S3
This option is specific to S3 stores and causes a user facing warning if
there are any errors when publishing to other store types like HTTPS:

    % ft publish --signing-private-key ~/tmp/signing.key
    Rendering hello-go build script to /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.HqDmOE/4453a787-hello-go-build.bash
    Building hello-go-unknown in local mode
    00:00:00.003576 + go build main.go
    00:00:00.099458 + mkdir -p /tmp/store_4453a7878a37650e58a20b2e316efe56-hello-go-unknown/bin
    00:00:00.101564 + cp main /tmp/store_4453a7878a37650e58a20b2e316efe56-hello-go-unknown/bin/hello-go
    this derivation will be built:
      /nix/store/69g61y3clvrdnkqfy19fmq60lf1lg5bd-hello-go-unknown.drv
    building '/nix/store/69g61y3clvrdnkqfy19fmq60lf1lg5bd-hello-go-unknown.drv'...
    hello-go-unknown> signing /nix/store/slfnasfanaigxlmi38bwnvky5jhimj69-hello-go-unknown
    hello-go-unknown> patching script interpreter paths in /nix/store/slfnasfanaigxlmi38bwnvky5jhimj69-hello-go-unknown/bin/hello-go
    Completed build of hello-go-unknown in local mode

    ❌ ERROR: Failed to publish package: Failed to upload to cache: warning: unknown setting 'ls-compression'
    error: 'https://cache.floxware.com/cache' does not appear to be a binary cache