fix(buildenv): Surface realise parallel errors
We regressed this when adding parallel realise/downloads because we were
only taking the outer error from the `handle.join` and ignoring the
inner error from `realise_*`.

For example, but not limited to, installing a custom package without the
correct `nix.conf` should return:

    % ft install flox/gcloud-with-auth
    ✘ ERROR: Failed to build environment:

    Package 'gcloud-with-auth' is not signed by a trusted key

Instead it would happily continuing to build an environment that didn't
have all of the packages realised and caused a more verbose error:

    % ft install flox/gcloud-with-auth
    ❌ ERROR: Failed to build environment:

    Failed to construct environment: error:
           … while calling the 'derivationStrict' builtin
             at <nix/derivation-internal.nix>:37:12:
               36|
               37|   strict = derivationStrict drvAttrs;
                 |            ^
               38|

           … while evaluating derivation 'environment'
             whose name attribute is located at /nix/store/646g6bi8k11ry19nfy345n84hr2hn43p-flox-buildenv-0.0.1/lib/buildenv.nix:279:11

           … while evaluating attribute 'exportReferencesGraph' of derivation 'environment'
             at /nix/store/646g6bi8k11ry19nfy345n84hr2hn43p-flox-buildenv-0.0.1/lib/buildenv.nix:352:3:
              351|   # the contents of requisites.txt for each output.
              352|   exportReferencesGraph.graph = inputSrcs ++ [
                 |   ^
              353|     interpreter_out

           (stack trace truncated; use '--show-trace' to show the full, detailed trace)

           error: path '/nix/store/wjz6ink2dzv5nnajlxinzkkx5w68a46i-gcloud-with-auth-537.0.0' does not exist and cannot be created

Fix this by preserving the pre-parallel behaviour of returning the first
error encountered, even though other errors may have occurred in
parallel. The order matches how the threads were started which is based
on locked packages grouped by base, custom, and storepath.

In the future we could be more clever about returning all errors, like
we do for catalog resolution errors, but it requires some design and
formatting work that I'm going to defer for now.