fix(flox-build): canonicalize log file path before adding to store
Log files created during manifest builds (at least during tests),
are written to a path under `/tmp`, e.g.:

    /tmp/nix-shell.ymmyR7/tmp.XIrchhtTVV-build-foo.log

On macos `/tmp` is actually a symlink to `/private/tmp`:

    $ realpath /tmp/nix-shell.ymmyR7/tmp.XIrchhtTVV-build-foo.log
    /private/tmp/nix-shell.ymmyR7/tmp.XIrchhtTVV-build-foo.log

Incidentally, in nix versions > 2.18 (i haven't tracked down exactly which version)
symlinked paths are no longer allowed as an argument to `nix store add-file`:

    nix store add-file "/tmp/nix-shell.ymmyR7/tmp.XIrchhtTVV-build-foo.log"
    error: path '/tmp' is a symlink

As a result we've seen errors in our macos CI:

    stderr: building '/nix/store/f8ryk7m9a7wcn31pdy3p3q87dds6vk57-foo-0.0.0.drv'...
    stderr: foo> signing /nix/store/8mjy7as35h57j6c9xwd91274snqny60v-foo-0.0.0
    stderr: foo> ⚠️  WARNING: No executables found in '$out/bin'.
    stderr: foo> Only executables in '$out/bin' will be available on the PATH.
    stderr: foo> If your build produces executables, make sure they are copied to '$out/bin'.
    stderr: foo>   - copy a single file with 'mkdir -p $out/bin && cp file $out/bin'
    stderr: foo>   - copy a bin directory with 'mkdir $out && cp -r bin $out'
    stderr: foo>   - copy multiple files with 'mkdir -p $out/bin && cp bin/* $out/bin'
    stderr: foo>   - copy files from an Autotools project with 'make install PREFIX=$out'
    stderr: foo (post)> OUT_PATHS: /nix/store/8mjy7as35h57j6c9xwd91274snqny60v-foo-0.0.0
    stderr: foo (post)> DRV_PATHS: /nix/store/f8ryk7m9a7wcn31pdy3p3q87dds6vk57-foo-0.0.0.drv
    stderr: error: path '/tmp' is a symlink
    stderr: path '/private/tmp/.tmpUOulfN/temp/.tmp7abw7c' does not contain a 'flake.nix', searching up
    stderr: error: could not find a flake.nix file
    stderr: make: *** [/Users/runner/work/flox/flox/build/flox-package-builder/libexec/flox-build.mk:426: foo_local_build] Error 1

This commit fixes the argument to `flox-build.mk` by canonicalizing it (`/tmp -> /private/tmp`) with `realpath`.

squash! fix(flox-build): canonicalize log file path before adding to store

Also canonicalize the path of the temporary flake used to build environments with flake inputs.