feat(nef): catalog closure from an externally supplied lockfile
Design partner work on NEF catalog imports uncovered a few issues:

1. projects depending on catalogs cause update cycles
   (especially if they are themselves part of the imported catalog)
2. diamond imports do not necessarily refer to the same
   package potentially causing incompatibilities.
3. its impossible to tell which packages should trigger rebuilds

This changes the requirements on the NEF import story:

* we prefer per package dependencies
* meaning, we also prefer per package

This commit does the main NEF change, that is 
* take an _externally supplied_ lockfile describing a full  dependency closure
* (lazily) instantiate these dependencies 
* pass the full closure as the `catalogs` arguemnt to all packages in the closure

fix: add missing instantiateFromSourceInfo attribute

Encounted following error with NEF library eval:

> error: function 'instantiateFromSourceInfo' called without required argument 'instantiatedCatalogsClosure'
> at /nix/store/lcyggx57cclp4ricbdk8b816jd72wban-package-builder-1.0.0/libexec/nef/lib/instantiate.nix:176:5:
>    175|   instantiateFromSourceInfo =
>    176|     {
>       |     ^
>    177|       nixpkgs,