fix: only mount flox.toml for macOS containerize
We've seen the following error when running macOS containerize tests

```
unpacking 'github:flox/flox/9bcabec338c849abcf2e35f1d9b359fcbdb033ff' into the Git cache...
error:
       … while fetching the input 'github:flox/flox/main'

       error: adding a file to a tree builder: failed to insert entry: invalid object specified - default.nix
```
https://github.com/flox/flox/actions/runs/13163465842/job/36737896328#step:5:470

Although we're not sure, this could be caused by mounting some of the
directories Nix uses in HOME inside the container.

The original reason to mount HOME was so that ~/.config/flox/flox.toml
would be respected. Instead of mounting all of HOME, just mount
flox.toml