fix(activations): OpenSSL for cargo bin in tests
Ensure that OpenSSL is in the closure for the cargo built
`flox-activations` binary that is used by unit tests on aarch64-linux.
They were failing after Sentry was added:

    thread 'providers::build::tests::build_cache_sandbox_pure_uses_cache' (31067) panicked at flox-rust-sdk/src/providers/build.rs:854:17:
    expected build to succeed: Build failed
    stderr: this derivation will be built:
      /nix/store/509i21v2gi0kh7sf9rxg1kx0m44x17lm-foo-0.0.0.drv
    building '/nix/store/509i21v2gi0kh7sf9rxg1kx0m44x17lm-foo-0.0.0.drv'...
    foo> ---
    foo> Input checksums:
    foo> 1276481102f218c981e0324180bafd9f  /nix/store/l9h3r8h1xzxi4w2ldz1jl7h3yygzskd3-src.tar
    foo> 60242999b5c5a48893a8fe0e6bb244f6  /nix/store/s7irckm5jhwy1ahk2zwnj13h37kw37gy-build.bash
    foo> ddea8953ba736538e450b338ef376c79  /nix/store/w9ybay4xjgg3fvc7p687r0zajqm8slaw-buildCache.tar
    foo> ---
    foo> /nix/store/5c7wbg79pdrcjfi9sl48qsyyl6bgf24n-flox-activations/libexec/flox-activations: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
    foo> /nix/store/5vjci65kvbcicg6fr81005xh49wy5l6v-developcopy-build-foo/activate: line 206: FLOX_ENV_DIRS: unbound variable
    foo> /nix/store/5vjci65kvbcicg6fr81005xh49wy5l6v-developcopy-build-foo/activate: line 229: FLOX_ENV_DIRS: unbound variable
    foo> find: '/nix/store/xq88q9mf3ph8bkim88bbb0lrjpy5wx92-foo-0.0.0': No such file or directory

We have to copy instead of symlink the binary because for
`propagatedBuildInputs` to work, AFAICT because the reference scanner
doesn't follow symlinks.