fix(manifest): skip_serializing_none for systemd
Prevent unset fields in `services.*.systemd` from being serialized as
`null` values in the lockfile.

It wouldn't have caused extra backwards-compat issues in this case
because you have to opt-in to setting some systemd fields and they won't
work with older Flox versions, but it does add unncessary bloat to the
lockfile.

The existing test didn't catch this because we bypassed proptest for the
child fields due to generating too many test cases. I've fixed this by
generating just enough to trip the test, which failed as follows prior
to adding the type attributes.

    thread 'models::manifest::typed::test::manifest_does_not_serialize_null_fields' panicked at flox-rust-sdk/src/models/manifest/typed.rs:1198:5:
    Test failed: json: {
      "version": 1,
      "options": {},
      "services": {
        "0": {
          "command": "0",
          "systemd": {
            "unit": {
              "description": null,
              "documentation": null,
              "wants": null,
              "requires": null,
              "before": null,
              "after": null
            },
            "service": {
              "type_": null,
              "exec_start": null,
              "exec_start_pre": null,
              "exec_start_post": null,
              "exec_stop": null,
              "restart": null,
              "restart_sec": null,
              "timeout_start_sec": null,
              "timeout_stop_sec": null,
              "cpu_quota": null,
              "cpu_shares": null,
              "cpu_weight": null,
              "memory_max": null,
              "memory_high": null,
              "memory_low": null,
              "tasks_max": null,
              "io_weight": null,
              "limit_cpu": null,
              "limit_fsize": null,
              "limit_data": null,
              "limit_stack": null,
              "limit_core": null,
              "limit_rss": null,
              "limit_nofile": null,
              "limit_as": null,
              "limit_nproc": null,
              "limit_memlock": null,
              "limit_locks": null,
              "limit_sigpending": null,
              "limit_msgqueue": null,
              "limit_nice": null,
              "limit_rtprio": null,
              "limit_rttime": null,
              "private_tmp": null,
              "protect_system": null,
              "protect_home": null,
              "no_new_privileges": null,
              "environment": null,
              "environment_file": null
            }
          }
        }
      }
    } at flox-rust-sdk/src/models/manifest/typed.rs:1202.