feat: Create theme system for prompt and logs (#88)
* Create theme system for prompt and logs

* feat: Add color system

* feat: Impl `flox_theme_ extension for inquire

* feat: print ambiguous package notice as error

Before all user facing information was printed as log statements (of different severity).
Log statements may be suppressed (esp. info is not printed by default).
The logs are also printed before the error message and might be overlooked.
This change Places the error information into the final error message.

TODO: make an abstractible error type.

New error message is saying:

```
Error: No terminal to prompt for package choice

Caused by:
    You must address a specific package. For example with:

        $ flox build flox,

    The available packages are:
      - flox
      - notflox
```

* feat: impl mutually exclusive `verbose` and `quiet` flags

* fixup: Show errors in quiet mode

* fixup: use default of `Verbose(0)` instead of `Quiet`

* refactor: return ExitCode from main, use run helper

* dep: add indoc

Co-authored-by: Yannik Sander <yannik@floxdev.com>