chore: empty commit to change git rev
It appears the Nix shortRev is ambiguous, which I think is causing
containerize tests to fail.
```
> nix eval --expr '(builtins.getFlake "github:flox/flox/4930308c3613faa2eb72404b3cf398d2c02bd637").shortRev' --raw
4930308%

> git show 4930308
error: short object ID 4930308 is ambiguous
hint: The candidates are:
hint:   4930308c3 commit 2025-12-26 - bump: 1.8.0 -> 1.8.1
hint:   4930308f5 blob
```

The tests are failing with:
```
error:
       … while fetching the input 'github:flox/flox/4930308'

       error: unable to download 'https://api.github.com/repos/flox/flox/commits/4930308': HTTP error 422

       response body:

       {
         "message": "No commit found for SHA: 4930308",
         "documentation_url": "https://docs.github.com/rest/commits/commits#get-a-commit",
         "status": "422"
       }
```