chore(flake): Update crane
To resolve these errors after adding a crate from git to `Cargo.toml`:

    % nix build
    evaluation warning: rustPlatform.fetchCargoTarball is deprecated in favor of rustPlatform.fetchCargoVendor.
                        If you are using buildRustPackage, try setting useFetchCargoVendor = true and regenerating cargoHash.
                        See the 25.05 release notes for more information.
    evaluation warning: rustPlatform.fetchCargoTarball is deprecated in favor of rustPlatform.fetchCargoVendor.
                        If you are using buildRustPackage, try setting useFetchCargoVendor = true and regenerating cargoHash.
                        See the 25.05 release notes for more information.
    evaluation warning: rustPlatform.fetchCargoTarball is deprecated in favor of rustPlatform.fetchCargoVendor.
                        If you are using buildRustPackage, try setting useFetchCargoVendor = true and regenerating cargoHash.
                        See the 25.05 release notes for more information.
    evaluation warning: rustPlatform.fetchCargoTarball is deprecated in favor of rustPlatform.fetchCargoVendor.
                        If you are using buildRustPackage, try setting useFetchCargoVendor = true and regenerating cargoHash.
                        See the 25.05 release notes for more information.
    evaluation warning: rustPlatform.fetchCargoTarball is deprecated in favor of rustPlatform.fetchCargoVendor.
                        If you are using buildRustPackage, try setting useFetchCargoVendor = true and regenerating cargoHash.
                        See the 25.05 release notes for more information.
    error: hash mismatch in fixed-output derivation '/nix/store/ggy6qc9y3icqsvasl92g2x0q29ifz303-crane-utils-0.0.1-vendor.tar.gz.drv':
             specified: sha256-yVe6BIUuZygz44GiPRWAjMCU9IbglyrS2RAuLcP+3Ls=
                got:    sha256-K0iqBrCnb3NE/2tQFSM5X9IzvJEm8iW2kxfuGHMWn/g=
    error: 1 dependencies of derivation '/nix/store/k11a2h532qyvniyg2p6zz0lw9zifg332-crane-utils-0.0.1.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/0ghh1jx8sb27lzrj06v35zzj919pkzf7-cargo-git.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/qrbd2ypbg809yhhqh6ncbs0z6laz4nad-linkLockedDeps.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/zd458gssh7lqc1krbigpl6pkgs70kmck-vendor-cargo-deps.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/309is4gkhqfr6k5dllnb2ga3iqiywzn7-flox-1.4.1.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/kd9fdjmf4bp78154bmzk5545iynsqb28-flox-activations-1.4.1.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/19l1l4b372qnph62zs601limrdyq2r8v-flox-1.4.1-g88ae04a.drv' failed to build

I'm not super clear, but my guess is that both the warning and the error
relate to this change from https://crane.dev/CHANGELOG.html

> craneUtils (used internally for vendoring git dependencies) now uses
> importCargoLock to fetch its own dependencies instead of the (now
> deprecated) fetchCargoTarball method.