fix(manifest): Add+test missing skip serialize
A manifest edited by current HEAD produces a lockfile with:

    % jq .manifest.build ~/tmp/.flox/env/manifest.lock
    {
      "hello2": {
        "command": "exit 1",
        "files": null,
        "runtime-packages": null,
        "systems": null,
        "sandbox": null,
        "version": null,
        "description": null,
        "license": null
      }
    }

Which can't be read by existing versions of Flox:

    % ft list
    ❌ ERROR: Failed to parse lockfile as JSON: unknown field `version`, expected one of `command`, `files`, `runtime-packages`, `systems`, `sandbox` at line 26 column 17

    This is likely due to a corrupt environment.

Prevent this from happening by adding `skip_serializing_none` to the
remaining child structs in the manifest and adding a test that prevents
us from regressing in the future.

Before the changes it would fail as follows:

    ---- models::manifest::test::manifest_does_not_serialize_null_fields stdout ----
    thread 'models::manifest::test::manifest_does_not_serialize_null_fields' panicked at flox-rust-sdk/src/models/manifest.rs:2369:5:
    Test failed: json: {
      "version": 1,
      "hook": {},
      "profile": {},
      "options": {
        "allow": {
          "licenses": []
        },
        "semver": {}
      },
      "build": {
        "A": {
          "command": "",
          "files": null,
          "runtime-packages": null,
          "systems": null,
          "sandbox": null,
          "version": null,
          "description": null,
          "license": null
        }
      }
    } at flox-rust-sdk/src/models/manifest.rs:2373.
    minimal failing input: manifest = Manifest {
        version: Version {
            value: 1,
        },
        install: ManifestInstall(
            {},
        ),
        vars: ManifestVariables(
            {},
        ),
        hook: ManifestHook {
            on_activate: None,
        },
        profile: ManifestProfile {
            common: None,
            bash: None,
            zsh: None,
            fish: None,
            tcsh: None,
        },
        options: ManifestOptions {
            systems: None,
            allow: Allows {
                unfree: None,
                broken: None,
                licenses: [],
            },
            semver: SemverOptions {
                allow_pre_releases: None,
            },
            cuda_detection: None,
        },
        services: ManifestServices(
            {},
        ),
        build: ManifestBuild(
            {
                "A": ManifestBuildDescriptor {
                    command: "",
                    files: None,
                    runtime_packages: None,
                    systems: None,
                    sandbox: None,
                    version: None,
                    description: None,
                    license: None,
                },
            },
        ),
        containerize: None,
    }