fix(build): pure build error when no $out
Raise a clearer error if a build script doesn't write anything to
`$out`. The provides parity with impure builds and fixes a bug where the
conditional for `! -e ${install-prefix-contents}` was never reached
because it failed eagerly.

It's worth noting that `$out` should not be interpolated because it has
a special user-facing meaning that they should reference in their build
commands and there won't be anything to inspect at the interpolated path
because this error is only triggered when the path doesn't exist.

The previous error looked like this:

    …
    foo> bar
    error: builder for '/nix/store/4kg7i9kf4n4dz4bc7323s4qhl6r1bkwx-foo-0.0.0.drv' failed to produce output path for output 'out' at '/nix/store/plkaihfglaj8s9h1vv7mzmahax3b2kxl-foo-0.0.0'
    make: *** [/nix/store/p341bwldmd3lv2yxq16pv6dndvmlzsmi-package-builder-1.0.0/libexec/flox-build.mk:317: foo_nix_sandbox_build] Error 1
    rm /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.V2I4sp/291fe2a7-foo-build.bash
    make: Leaving directory '/Users/dcarley/tmp'
    ❌ ERROR: Build failed with status: exit status: 2

The revised error looks like this:

    …
    foo> ERROR: Build command did not copy outputs to '$out'.
    foo> - copy a single file with 'cp bin $out'
    foo> - copy multiple files with 'mkdir -p $out && cp bin/* $out/'
    foo> - copy files from an Autotools project with 'make install PREFIX=$out'
    error: builder for '/nix/store/v3xg9qahnxjx9dizzapi94p53b7bba0w-foo-0.0.0.drv' failed with exit code 1;
           last 10 log lines:
           > calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/ngg1cv31c8c7bcm2n8ww4g06nq7s4zhm-set-source-date-epoch-to-latest.sh
           > calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh
           > calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/505k98rmay60a12qn7bdz3fxfyx5wnr6-environment
           > calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/04w1mgkhawycg64s4q3n8mkcvma5ppx0-apple-framework-CoreFoundation-11.0.0
           > calling 'envHostTargetHook' function hook 'sdkRootHook' /nix/store/lybzq28v1ay0zac24hp0pw38s76ijvsj-libobjc-11.0.0
           > /nix/store/8ai7wnasb4sw2v410arjnsz7ha70xn7p-foo-0.0.0
           > ERROR: Build command did not copy outputs to '$out'.
           > - copy a single file with 'cp bin $out'
           > - copy multiple files with 'mkdir -p $out && cp bin/* $out/'
           > - copy files from an Autotools project with 'make install PREFIX=$out'
           For full logs, run 'nix log /nix/store/v3xg9qahnxjx9dizzapi94p53b7bba0w-foo-0.0.0.drv'.
    make: *** [/nix/store/xxb9n6barfjhb0kqswbd80ydpspxpk0i-package-builder-1.0.0/libexec/flox-build.mk:317: foo_nix_sandbox_build] Error 1
    rm /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.s6s3h4/903821b4-foo-build.bash
    make: Leaving directory '/Users/dcarley/tmp'
    ❌ ERROR: Build failed with status: exit status: 2