fix: don't clear environment for build activation
Clearing the environment is preventing variables set by the outer
activation from getting in to the inner activation.

More specifically, when trying to `flox build`
https://github.com/flox/flox-manifest-build-examples/tree/f8285e85c90144328b5540cbf596fb9c4f138770/quotes-app-cpp
we get the error:
```
Rendering quotes-cpp build script to /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T//9b780511-quotes-cpp-build.bash
Building quotes-cpp-0.0.1 in local mode
00:00:00.003944 + mkdir -p /tmp/store_9b780511826ebac591134b75268ca2e1-quotes-cpp-0.0.1/bin /tmp/store_9b780511826ebac591134b75268ca2e1-quotes-cpp-0.0.1/lib /tmp/store_9b780511826ebac591134b75268ca2e1-quotes-cpp-0.0.1/libexec
00:00:00.038850 clang++ -O3 -std=c++17 quotes_server.cpp -o quotes-cpp -lboost_system -lboost_json -pthread
00:00:00.005831 + make
00:00:01.635954 quotes_server.cpp:1:10: fatal error: 'boost/beast.hpp' file not found
00:00:01.635977     1 | #include <boost/beast.hpp>
00:00:01.635979       |          ^~~~~~~~~~~~~~~~~
00:00:01.927974 1 error generated.
00:00:01.929584 make: *** [all] Error 1
make: *** [/nix/store/z99p3mq6fqhajls0fcisdnqlay2jwcpq-package-builder-1.0.0/libexec/flox-build.mk:456: quotes_cpp_local_build] Error 2
❌ ERROR: Build failed with status: exit status: 2
```

Includes cannot be found because "$FLOX_ENV/include" only exists for the
outer activation, not the inner one, but we're clearing the environment
between the two activations.

TODO: need more discussion about whether we want to choose what parts of
outer activation to allow in, or if there are parts of outer activation
that we want to keep out