fix: add missing instantiateFromSourceInfo attribute
Encounted following error with NEF library eval:

> error: function 'instantiateFromSourceInfo' called without required argument 'instantiatedCatalogsClosure'
> at /nix/store/lcyggx57cclp4ricbdk8b816jd72wban-package-builder-1.0.0/libexec/nef/lib/instantiate.nix:176:5:
>    175|   instantiateFromSourceInfo =
>    176|     {
>       |     ^
>    177|       nixpkgs,