fix: unset outer LIBRARY_PATH for impure builds
LIBRARY_PATH can pull the development closure into the built artifact
closure, which causes the build to fail with
```
error: output '/nix/store/XXX' is not allowed to refer to the following paths
...
```