fix: drop --bash-passthru
- Drop Bash code
- Drop Rust code implementing --bash-passthru
- Make develop an alias of activate
- Mark generations, history, push, pull, rollback, upgrade, auth with
  todo!("this command is planned for a future release")
  Running one of these commands will result in the output:
  thread 'main' panicked at 'not yet implemented: this command is planned for a future release', crates/flox/src/commands/environment.rs:621:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
- Mark export, import, print-dev-env with
  todo!("deprecated")
  These commands will be dropped in a followup PR
- Mark git, rollback, switch-generations, gh with
  todo!("TODO")