fix: in-place activation for Bash 3
In-place activation with Bash 3 currently errors with:
```
Error: Broken pipe (os error 32)
```

This is caused by using `source <(...)`, because Bash 3 does not support
process substitution with source. See:
https://lists.gnu.org/archive/html/bug-bash/2006-01/msg00018.html

Fix this by using `eval` instead of `source`