test: do not set `USER` in integration tests
Setting users causes flox to override USER and HOME back to the effective user's.
In effect, `flox activate` during integration tests will run the effective user's rcfiles.

fix: set `USER` to avoid podman failures
Running `containerize` tests using the github user caused podman to err with

```
Error: command required for rootless mode with multiple IDs: exec: "newuidmap": executable file not found in $PATH
```

Promptly installing `shadow` to provide `newuidmap` however causes the following error:

```
# time="2024-11-06T19:12:54Z" level=error msg="running `/nix/store/xi2asrhj9m8vzcg4zmp03947vsjd25x2-shadow-4.16.0/bin/newuidmap 2393938 0 1015 1 1 689824 65536`: newuidmap: write to uid_map failed: Operation not permitted\n"
# Error: cannot set up namespace using "/nix/store/xi2asrhj9m8vzcg4zmp03947vsjd25x2-shadow-4.16.0/bin/newuidmap": should have setuid or have filecaps setuid: exit status 1
```

Against common sense, instead of providing newuidmap,
setting an arbitrary `USER=podman-test` causes the tests to succeed.

The reason for this is still somewhat nebulous but it seems to work.

test: do not set `USER` in integration tests

Avoid diagnostic logs of custom *rc file to be inspected as output in tests that dont expect it