fix: backport concurrent gc issue to nix 2.18
We ran into occasional issues with the nix gc-socket in our unit test suite.
<https://github.com/flox/flox/issues/2116> was logged against it to investigate.
The error we are seeing is:

    error: cannot connect to socket at '/nix/var/nix/gc-socket/socket': No such file or directory

Which appears to be discussed upstream in <https://github.com/NixOS/nix/issues/7370>.
The upstream issue was closed via <https://github.com/NixOS/nix/commit/c5fdbdae321903740e0e735aa89fab5647992687>
but only on nix >=2.20.
nix 2.18, the current stable version used by flox,
still uses the existing implementation:
<https://github.com/NixOS/nix/blob/d4d300c2084b5e81ee0ea2aba8215d03133f14f8/src/libstore/gc.cc#L145-L151>.

This commit adds the upstream changes as a patch,
until nixpkgs upgrades to nix > 2.18 for good.
The patch was amended by removing testing related hunks
that don't apply.