feat: report nix errors when installing flakes (#1794)
## Proposed Changes

<!-- Describe the changes proposed in this pull request. -->
<!-- Please provide links to any issue(s) which are expected to be
resolved. -->
Reports Nix errors when installing flakes. This additionally exits on
the first error rather than failing on all four systems and reporting
the same error four times.

```
chonker:flake-eval-errors zmitchell$ flox install github:cachix/cachix
❌ ERROR: resolution failed: Failed to lock flake installable: error:
       … in the left operand of the update (//) operator

         at /nix/store/j4jzjbr302cw5bl0n3pch5j9bh5qwmaj-source/pkgs/development/haskell-modules/lib/compose.nix:40:7:

           39|     mkDerivation = drv: (args.mkDerivation drv).override f;
           40|   })) // {
             |       ^
           41|     overrideScope = scope: overrideCabal f (drv.overrideScope scope);

       … while evaluating the attribute 'cachix'

         at /nix/store/zj0liwzarhzpkmy3247vv6icdaz77ma7-source/flake.nix:40:7:

           39|       cachix-api = haskellPackages.callCabal2nix "cachix-api" ./cachix-api {};
           40|       cachix = haskellPackages.callCabal2nix "cachix" ./cachix {
             |       ^
           41|         inherit cachix-api;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: cannot build '/nix/store/1dm1w7za4l3s9bml7pkdkrlcxrvz9255-cabal2nix-cachix.drv' during evaluation because the option 'allow-import-from-derivation' is disabled
```

## Release Notes

<!-- Describe any user facing changes. Use "N/A" if not applicable. -->
N/A

<!-- Many thanks! -->