refactor(compose): Warning::Placeholder variant
To stop linting complaining about:

    error: this `.filter_map` can be written more simply
    --> flox/src/utils/message.rs:130:62
        |
    130 |       let winning_env_by_field: BTreeMap<Field, Environment> = compose
        |  ______________________________________________________________^
    131 | |         .warnings
    132 | |         .iter()
    133 | |         .filter_map(|warning_context| match &warning_context.warning {
    ...   |
    137 | |             )),
    138 | |         })
        | |__________^ help: try instead: `map`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_filter_map
        = note: `-D clippy::unnecessary-filter-map` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(clippy::unnecessary_filter_map)]`

Or:

    error: irrefutable `if let` pattern
    --> flox/src/utils/message.rs:134:16
        |
        134 |             if let Warning::Overriding(field) = &warning_context.warning {
        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = note: this pattern will always match, so the `if let` is useless
        = help: consider replacing the `if let` with a `let`
        = note: `-D irrefutable-let-patterns` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(irrefutable_let_patterns)]`

And using a plain `let` to extract the `KeyPath` would still require
changing this callsite when adding a new variant in the future.