fix: better env name error message (#915)
## Proposed Changes

<!-- Describe the changes proposed in this pull request. -->
<!-- Please provide links to any issue(s) which are expected to be
resolved. -->
Adds an error handling layer above parsing environment names so that a
more informative error message can be shown to the user.

```
$ flox init --name foo/bar
ERROR: Name 'foo/bar' is invalid. Environment names may not contain ' ' or '/'.
```

## Release Notes

<!-- Describe any user facing changes. Use "N/A" if not applicable. -->
N/A

<!-- Many thanks! -->