test: wait_for_watchdogs || return 1
Calling `exit 1` from `teardown` causes the output from any failing
assertions to be lost and the test considered not run (or failed). This
made it very hard to debug the following failures in CI:

- https://github.com/flox/flox/actions/runs/12179971098/job/33973716420
- https://github.com/flox/flox/actions/runs/12180093654/job/33973739414
- https://github.com/flox/flox/actions/runs/12179430940/job/33971646882
- https://github.com/flox/flox/actions/runs/12158758725/job/33907492506

I experimented with unsetting `BATS_TEST_COMPLETED` instead of catching
the return code in each `teardown` but I have low confidence that the
behaviour might change in future without us realising:

- https://bats-core.readthedocs.io/en/stable/faq.html#how-can-i-check-if-a-test-failed-succeeded-during-teardown

A simpler reproduction of tests that should fail with output:

    @test "wip: stray activation with failing assertion" {
      "$FLOX_BIN" init
      "$FLOX_BIN" activate -- sleep 15 &
      run "$FLOX_BIN" activate -- false
      assert_success
    }

    @test "wip: stray activation with passing assertion" {
      "$FLOX_BIN" init
      "$FLOX_BIN" activate -- sleep 15 &
      run "$FLOX_BIN" activate -- true
      assert_success
    }

    @test "wip: stray activation with inline wait_for_watchdogs" {
      "$FLOX_BIN" init
      "$FLOX_BIN" activate -- sleep 15 &
      sleep 1 # allow watchdog to start
      wait_for_watchdogs "$PROJECT_DIR"
    }

Previously this would output, with logs and processes omitted:

    ERROR: flox-watchdog processes did not finish after 10 seconds
    ERROR: flox-watchdog processes did not finish after 10 seconds
    not ok 2 wip: stray activation with passing assertion in 14518ms
    # tags: services
    # (from function `wait_for_watchdogs' in file test_support.bash, line 222,
    #  from function `teardown' in test file services.bats, line 91)
    #   `wait_for_watchdogs "$PROJECT_DIR"' failed
    # ✨ Created environment 'test' (aarch64-darwin)
    #
    # Next:
    #   $ flox search <package>    <- Search for a package
    #   $ flox install <package>   <- Install a package into an environment
    #   $ flox activate            <- Enter the environment
    #   $ flox edit                <- Add environment variables and shell hooks
    #
    ERROR: flox-watchdog processes did not finish after 10 seconds
    not ok 3 wip: stray activation with inline wait_for_watchdogs in 16116ms
    # tags: services
    # (from function `wait_for_watchdogs' in file test_support.bash, line 222,
    #  in test file services.bats, line 1554)
    #   `wait_for_watchdogs "$PROJECT_DIR"' failed
    # ✨ Created environment 'test' (aarch64-darwin)
    #
    # Next:
    #   $ flox search <package>    <- Search for a package
    #   $ flox install <package>   <- Install a package into an environment
    #   $ flox activate            <- Enter the environment
    #   $ flox edit                <- Add environment variables and shell hooks
    #
    # bats warning: Executed 2 instead of expected 3 tests
    error: Recipe `integ-tests` failed on line 85 with exit code 1

Now it will output, with logs and processes omitted:

    ERROR: flox-watchdog processes did not finish after 10 seconds
    not ok 1 wip: stray activation with failing assertion in 13872ms
    # tags: services
    # (from function `assert_success' in file /nix/store/h7inz07x6739s38i02532g5pj6dlnx8k-bats-with-libraries-1.11.0/share/bats/bats-assert/src/assert_success.bash, line 42,
    #  in test file services.bats, line 1540)
    #   `assert_success' failed
    # ✨ Created environment 'test' (aarch64-darwin)
    #
    # Next:
    #   $ flox search <package>    <- Search for a package
    #   $ flox install <package>   <- Install a package into an environment
    #   $ flox activate            <- Enter the environment
    #   $ flox edit                <- Add environment variables and shell hooks
    #
    #
    # -- command failed --
    # status : 1
    # output :
    # --
    #
    ERROR: flox-watchdog processes did not finish after 10 seconds
    not ok 2 wip: stray activation with passing assertion in 14495ms
    # tags: services
    # (from function `teardown' in test file services.bats, line 91)
    #   `wait_for_watchdogs "$PROJECT_DIR" || return 1' failed
    # ✨ Created environment 'test' (aarch64-darwin)
    #
    # Next:
    #   $ flox search <package>    <- Search for a package
    #   $ flox install <package>   <- Install a package into an environment
    #   $ flox activate            <- Enter the environment
    #   $ flox edit                <- Add environment variables and shell hooks
    #
    ERROR: flox-watchdog processes did not finish after 10 seconds
    not ok 3 wip: stray activation with inline wait_for_watchdogs in 16095ms
    # tags: services
    # (from function `wait_for_watchdogs' in file test_support.bash, line 234,
    #  in test file services.bats, line 1554)
    #   `wait_for_watchdogs "$PROJECT_DIR"' failed
    # ✨ Created environment 'test' (aarch64-darwin)
    #
    # Next:
    #   $ flox search <package>    <- Search for a package
    #   $ flox install <package>   <- Install a package into an environment
    #   $ flox activate            <- Enter the environment
    #   $ flox edit                <- Add environment variables and shell hooks
    #
    error: Recipe `integ-tests` failed on line 85 with exit code 1