fix: use newer numpy with available prebuilds
Python tests requiring numpy (1.26.x) caused failures attempting
to build numpy from source.
This appeared to fail upon missing a compiler suite
in the test environment:

```
Creating python virtual environment in /tmp/bats-run-KTSWIA/test/429/project-4/.flox/cache/python
  error: subprocess-exited-with-error
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Traceback (most recent call last):
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/cache/python/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/cache/python/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/cache/python/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 178, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-upemsc1g/overlay/lib/python3.13/site-packages/mesonpy/__init__.py", line 985, in wrapper
          return func(*args, **kwargs)
        File "/tmp/pip-build-env-upemsc1g/overlay/lib/python3.13/site-packages/mesonpy/__init__.py", line 1038, in build_wheel
          with _project(config_settings) as project:
               ~~~~~~~~^^^^^^^^^^^^^^^^^
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/run/aarch64-linux.project-4.dev/lib/python3.13/contextlib.py", line 141, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-upemsc1g/overlay/lib/python3.13/site-packages/mesonpy/__init__.py", line 912, in _project
          yield Project(source_dir, build_dir, meson_args, editable_verbose)
                ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-upemsc1g/overlay/lib/python3.13/site-packages/mesonpy/__init__.py", line 637, in __init__
          self._ninja = _env_ninja_command()
                        ~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-upemsc1g/overlay/lib/python3.13/site-packages/mesonpy/__init__.py", line 962, in _env_ninja_command
          version = subprocess.run([ninja_path, '--version'], check=False, text=True, capture_output=True).stdout
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/run/aarch64-linux.project-4.dev/lib/python3.13/subprocess.py", line 554, in run
          with Popen(*popenargs, **kwargs) as process:
               ~~~~~^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/run/aarch64-linux.project-4.dev/lib/python3.13/subprocess.py", line 1039, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              pass_fds, cwd, env,
                              ^^^^^^^^^^^^^^^^^^^
          ...<5 lines>...
                              gid, gids, uid, umask,
                              ^^^^^^^^^^^^^^^^^^^^^^
                              start_new_session, process_group)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/run/aarch64-linux.project-4.dev/lib/python3.13/subprocess.py", line 1857, in _execute_child
          self._posix_spawn(args, executable, env, restore_signals, close_fds,
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            p2cread, p2cwrite,
                            ^^^^^^^^^^^^^^^^^^
                            c2pread, c2pwrite,
                            ^^^^^^^^^^^^^^^^^^
                            errread, errwrite)
                            ^^^^^^^^^^^^^^^^^^
        File "/tmp/bats-run-KTSWIA/test/429/project-4/.flox/run/aarch64-linux.project-4.dev/lib/python3.13/subprocess.py", line 1801, in _posix_spawn
          self.pid = os.posix_spawn(executable, args, env, **kwargs)
                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-env-upemsc1g/normal/bin/ninja'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Activating python virtual environment
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/bats-run-KTSWIA/test/429/project-4/project/__main__.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

fix(lang-python): provide libstdc++ on linux

Newer releases of numpy (here 2.4.0) dynamically
link to `libstdc++.so.6`.
Since tests run in rather pure envronments
this causes new errors on linux specifically.
Installing gcc-unwrapped into the python environments
provides a working copy of `libstdc++.so.6`.