test: fix race in test_process_states_read
I've seen the failure:
```
thread ‘providers::services::tests::test_process_states_read’ panicked at flox-rust-sdk/src/providers/services.rs:1410:9:
assertion failed: `(left == right)`
Diff < left / right > :
<Running
>Completed
```

There's a race between when we run `process-compose list` and when
short-lived processes exit. Poll for processes to complete rather than
assuming they have completed the first time `process-compose list`
succeeds.