refactor(publish): Disable large_enum_variant
I expect this to go away when we implement the `Publisher` variant and
it doesn't seem worth boxing the URLs in the meantime.

    error: large size difference between variants
       --> flox-rust-sdk/src/providers/publish.rs:151:1
        |
    151 | /  pub enum ClientSideCatalogStoreConfig {
    152 | |      /// A `nix copy`-compatible Catalog Store (typically an S3 bucket).
    153 | |/     NixCopy {
    154 | ||         /// Where signed artifacts are uploaded to.
    155 | ||         ingress_uri: Url,
    156 | ||         /// Where artifacts are downloaded from.
    ...   ||
    161 | ||         auth_netrc_path: PathBuf,
    162 | ||     },
        | ||_____- the largest variant contains at least 224 bytes
    163 | |      /// A Catalog Store which only accepts metadata uploads.
    164 | |      MetadataOnly,
        | |      ------------ the second-largest variant carries no data at all
    ...   |
    169 | |      Publisher,
    170 | |  }
        | |__^ the entire enum is at least 224 bytes
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
        = note: `-D clippy::large-enum-variant` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(clippy::large_enum_variant)]`
    help: consider boxing the large fields to reduce the total size of the enum
        |
    157 |         egress_uri: Box<Url>,
        |                     ~~~~~~~~