feat: ensure sequential ordering of floxmeta creation
Use file locks to ensure that multiple processes
do not concurrently attempt to clone the upstream floxmeta repos.

Git has limited safeguards for this situation,
most of which are to detect concurrent usage via file locks,
fail fast and clean up intermediate state if possible.

E.g. concurrent clones will first copy template files,
and fails if another process created the same file earlier.

```
$ git clone <url> . & git clone <url> .

[..]

fatal: cannot copy '[..]/share/git-core/templates/info/exclude' to '[..]/info/exclude': File exists
```

Disabling template files will result in concurrent attempts
to lock files in the repository data dir:

```
$ export GIT_TEMPLATE_DIR=
$ git clone <url> . & git clone <url> .

error: could not lock config file [..]/.git/config: File exists
```

This change tries to avoid this specific race condition
by employing a separate flox managed file lock around the open or clone
logic of `ManagedEnvironment::open`.

It is unclear to which extend flox should inherit/depend on
or prevent git's behavior.
Short term this is used during environment opening of environments only,
a broader solution (e.g. on a per environment/command level)
might follow later when requirements are clearer