feat: error message when no search results (#390)
## Proposed Changes

<!-- Describe the changes proposed in this pull request. -->
<!-- Please provide links to any issue(s) which are expected to be
resolved. -->
When a search returns no results, an error message is displayed.

```
$ flox search surely_doesnt_exist
ERROR: No packages matched this search term: surely_doesnt_exist
```

## Release Notes

<!-- Describe any user facing changes. Use "N/A" if not applicable. -->
An error message is printed when no search results are found, and the
process exits unsuccessfully.

<!-- Many thanks! -->