test: fix test_rev_count
test_rev_count is failing for me with:
```
thread 'providers::git::tests::test_rev_count' panicked at flox-rust-sdk/src/providers/git.rs:1248:49:
called `Result::unwrap()` on an `Err` value: DoesNotExist
```

I think this is due to my git defaulting to `main` instead of `master`.
Use `branch_1` for consistency with other tests instead.

Also use the repo returned by `init_temp_repo()`