chore(watchdog): Temporarily disable Sentry
This is failing sandbox pure builds on x86_64-linux due to a missing
dependency in `flox-activations` that I can't figure out right now.

We'll want to reinstate Sentry for the executive/watchdog because it's
our indication of failures once it's detached from the terminal.

    thread 'providers::build::tests::boost_runtime_sandbox_pure' panicked at flox-rust-sdk/src/providers/build.rs:854:17:
    expected build to succeed: Build failed
    stderr: warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
    warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
    warning: AWS error uploading 'nix-cache-info': Access Denied (request id: E1C2XFE4EMA69AX6)
    this derivation will be built:
      /nix/store/mqmaks8haizqyk4k90xa3fhn3q5vl7aw-test_boost-0.0.0.drv
    building '/nix/store/mqmaks8haizqyk4k90xa3fhn3q5vl7aw-test_boost-0.0.0.drv'...
    test_boost> ---
    test_boost> Input checksums:
    test_boost> b664fbd1a9874fd456bdc55b403a7158  /nix/store/ywbx675cyxq27x8a5a0ykmqsm3q5d74y-src.tar
    test_boost> b73adb759066a01ae053d31126385bc2  /nix/store/5civ3rsa7v8z4rls5nx5qbvxgyy5mpkg-build.bash
    test_boost> 1b728ba48a4bf35a4d368892e24939fd  /nix/store/7ldp8q57y00vc1v3mlzq2s5cfsbvd5nd-buildCache.tar
    test_boost> ---
    test_boost> /nix/store/42wxp3npml4r2cymn3506wfhhwh0xlvl-flox-activations/libexec/flox-activations: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
    test_boost> /nix/store/1ksdkvk46scjvqc4zx11mb1yiwgxd6yy-developcopy-build-test_boost/activate: line 215: FLOX_ENV_DIRS: unbound variable
    test_boost> /nix/store/1ksdkvk46scjvqc4zx11mb1yiwgxd6yy-developcopy-build-test_boost/activate: line 247: FLOX_ENV_DIRS: unbound variable
    test_boost> flox build failed (caching build dir)